// Generated by gencpp from file tr_main/PlanParamRequest.msg
// DO NOT EDIT!


#ifndef TR_MAIN_MESSAGE_PLANPARAMREQUEST_H
#define TR_MAIN_MESSAGE_PLANPARAMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tr_main
{
template <class ContainerAllocator>
struct PlanParamRequest_
{
  typedef PlanParamRequest_<ContainerAllocator> Type;

  PlanParamRequest_()
    : i(0)  {
    }
  PlanParamRequest_(const ContainerAllocator& _alloc)
    : i(0)  {
  (void)_alloc;
    }



   typedef int64_t _i_type;
  _i_type i;




  typedef boost::shared_ptr< ::tr_main::PlanParamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tr_main::PlanParamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlanParamRequest_

typedef ::tr_main::PlanParamRequest_<std::allocator<void> > PlanParamRequest;

typedef boost::shared_ptr< ::tr_main::PlanParamRequest > PlanParamRequestPtr;
typedef boost::shared_ptr< ::tr_main::PlanParamRequest const> PlanParamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tr_main::PlanParamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tr_main::PlanParamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tr_main

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tr_main': ['/home/gagne/catkin_ws/src/tr_main/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tr_main::PlanParamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tr_main::PlanParamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tr_main::PlanParamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tr_main::PlanParamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tr_main::PlanParamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tr_main::PlanParamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tr_main::PlanParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "941a7affc871e5d970ac9ca6979081c3";
  }

  static const char* value(const ::tr_main::PlanParamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x941a7affc871e5d9ULL;
  static const uint64_t static_value2 = 0x70ac9ca6979081c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::tr_main::PlanParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tr_main/PlanParamRequest";
  }

  static const char* value(const ::tr_main::PlanParamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tr_main::PlanParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 i\n\
";
  }

  static const char* value(const ::tr_main::PlanParamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tr_main::PlanParamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.i);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanParamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tr_main::PlanParamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tr_main::PlanParamRequest_<ContainerAllocator>& v)
  {
    s << indent << "i: ";
    Printer<int64_t>::stream(s, indent + "  ", v.i);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TR_MAIN_MESSAGE_PLANPARAMREQUEST_H
