// Generated by gencpp from file tr_main/PlanParam.msg
// DO NOT EDIT!


#ifndef TR_MAIN_MESSAGE_PLANPARAM_H
#define TR_MAIN_MESSAGE_PLANPARAM_H

#include <ros/service_traits.h>


#include <tr_main/PlanParamRequest.h>
#include <tr_main/PlanParamResponse.h>


namespace tr_main
{

struct PlanParam
{

typedef PlanParamRequest Request;
typedef PlanParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanParam
} // namespace tr_main


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tr_main::PlanParam > {
  static const char* value()
  {
    return "3c371c8ad511ad64ee4f26a093142f3b";
  }

  static const char* value(const ::tr_main::PlanParam&) { return value(); }
};

template<>
struct DataType< ::tr_main::PlanParam > {
  static const char* value()
  {
    return "tr_main/PlanParam";
  }

  static const char* value(const ::tr_main::PlanParam&) { return value(); }
};


// service_traits::MD5Sum< ::tr_main::PlanParamRequest> should match 
// service_traits::MD5Sum< ::tr_main::PlanParam > 
template<>
struct MD5Sum< ::tr_main::PlanParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tr_main::PlanParam >::value();
  }
  static const char* value(const ::tr_main::PlanParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tr_main::PlanParamRequest> should match 
// service_traits::DataType< ::tr_main::PlanParam > 
template<>
struct DataType< ::tr_main::PlanParamRequest>
{
  static const char* value()
  {
    return DataType< ::tr_main::PlanParam >::value();
  }
  static const char* value(const ::tr_main::PlanParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tr_main::PlanParamResponse> should match 
// service_traits::MD5Sum< ::tr_main::PlanParam > 
template<>
struct MD5Sum< ::tr_main::PlanParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tr_main::PlanParam >::value();
  }
  static const char* value(const ::tr_main::PlanParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tr_main::PlanParamResponse> should match 
// service_traits::DataType< ::tr_main::PlanParam > 
template<>
struct DataType< ::tr_main::PlanParamResponse>
{
  static const char* value()
  {
    return DataType< ::tr_main::PlanParam >::value();
  }
  static const char* value(const ::tr_main::PlanParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TR_MAIN_MESSAGE_PLANPARAM_H
