// Generated by gencpp from file tkrb2018/PlanQueue.msg
// DO NOT EDIT!


#ifndef TKRB2018_MESSAGE_PLANQUEUE_H
#define TKRB2018_MESSAGE_PLANQUEUE_H

#include <ros/service_traits.h>


#include <tkrb2018/PlanQueueRequest.h>
#include <tkrb2018/PlanQueueResponse.h>


namespace tkrb2018
{

struct PlanQueue
{

typedef PlanQueueRequest Request;
typedef PlanQueueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanQueue
} // namespace tkrb2018


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tkrb2018::PlanQueue > {
  static const char* value()
  {
    return "e9c8148b4afb7a4d9a562439d8d7bbc9";
  }

  static const char* value(const ::tkrb2018::PlanQueue&) { return value(); }
};

template<>
struct DataType< ::tkrb2018::PlanQueue > {
  static const char* value()
  {
    return "tkrb2018/PlanQueue";
  }

  static const char* value(const ::tkrb2018::PlanQueue&) { return value(); }
};


// service_traits::MD5Sum< ::tkrb2018::PlanQueueRequest> should match 
// service_traits::MD5Sum< ::tkrb2018::PlanQueue > 
template<>
struct MD5Sum< ::tkrb2018::PlanQueueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tkrb2018::PlanQueue >::value();
  }
  static const char* value(const ::tkrb2018::PlanQueueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tkrb2018::PlanQueueRequest> should match 
// service_traits::DataType< ::tkrb2018::PlanQueue > 
template<>
struct DataType< ::tkrb2018::PlanQueueRequest>
{
  static const char* value()
  {
    return DataType< ::tkrb2018::PlanQueue >::value();
  }
  static const char* value(const ::tkrb2018::PlanQueueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tkrb2018::PlanQueueResponse> should match 
// service_traits::MD5Sum< ::tkrb2018::PlanQueue > 
template<>
struct MD5Sum< ::tkrb2018::PlanQueueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tkrb2018::PlanQueue >::value();
  }
  static const char* value(const ::tkrb2018::PlanQueueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tkrb2018::PlanQueueResponse> should match 
// service_traits::DataType< ::tkrb2018::PlanQueue > 
template<>
struct DataType< ::tkrb2018::PlanQueueResponse>
{
  static const char* value()
  {
    return DataType< ::tkrb2018::PlanQueue >::value();
  }
  static const char* value(const ::tkrb2018::PlanQueueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TKRB2018_MESSAGE_PLANQUEUE_H
