// Generated by gencpp from file tkrb2018/PlanQueueResponse.msg
// DO NOT EDIT!


#ifndef TKRB2018_MESSAGE_PLANQUEUERESPONSE_H
#define TKRB2018_MESSAGE_PLANQUEUERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tkrb2018
{
template <class ContainerAllocator>
struct PlanQueueResponse_
{
  typedef PlanQueueResponse_<ContainerAllocator> Type;

  PlanQueueResponse_()
    : task()
    , param(0.0)  {
    }
  PlanQueueResponse_(const ContainerAllocator& _alloc)
    : task(_alloc)
    , param(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _task_type;
  _task_type task;

   typedef double _param_type;
  _param_type param;




  typedef boost::shared_ptr< ::tkrb2018::PlanQueueResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tkrb2018::PlanQueueResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlanQueueResponse_

typedef ::tkrb2018::PlanQueueResponse_<std::allocator<void> > PlanQueueResponse;

typedef boost::shared_ptr< ::tkrb2018::PlanQueueResponse > PlanQueueResponsePtr;
typedef boost::shared_ptr< ::tkrb2018::PlanQueueResponse const> PlanQueueResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tkrb2018::PlanQueueResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tkrb2018::PlanQueueResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tkrb2018

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tkrb2018::PlanQueueResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tkrb2018::PlanQueueResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tkrb2018::PlanQueueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tkrb2018::PlanQueueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tkrb2018::PlanQueueResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tkrb2018::PlanQueueResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tkrb2018::PlanQueueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd3e0a41618412ecec32a87de6c56b93";
  }

  static const char* value(const ::tkrb2018::PlanQueueResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd3e0a41618412ecULL;
  static const uint64_t static_value2 = 0xec32a87de6c56b93ULL;
};

template<class ContainerAllocator>
struct DataType< ::tkrb2018::PlanQueueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tkrb2018/PlanQueueResponse";
  }

  static const char* value(const ::tkrb2018::PlanQueueResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tkrb2018::PlanQueueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string task\n\
float64 param\n\
\n\
";
  }

  static const char* value(const ::tkrb2018::PlanQueueResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tkrb2018::PlanQueueResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task);
      stream.next(m.param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanQueueResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tkrb2018::PlanQueueResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tkrb2018::PlanQueueResponse_<ContainerAllocator>& v)
  {
    s << indent << "task: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.task);
    s << indent << "param: ";
    Printer<double>::stream(s, indent + "  ", v.param);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKRB2018_MESSAGE_PLANQUEUERESPONSE_H
