// Generated by gencpp from file tr_main/PlanCommand.msg
// DO NOT EDIT!


#ifndef TR_MAIN_MESSAGE_PLANCOMMAND_H
#define TR_MAIN_MESSAGE_PLANCOMMAND_H

#include <ros/service_traits.h>


#include <tr_main/PlanCommandRequest.h>
#include <tr_main/PlanCommandResponse.h>


namespace tr_main
{

struct PlanCommand
{

typedef PlanCommandRequest Request;
typedef PlanCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanCommand
} // namespace tr_main


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tr_main::PlanCommand > {
  static const char* value()
  {
    return "968b0f0f66bd4a76a5a33813ca378fb1";
  }

  static const char* value(const ::tr_main::PlanCommand&) { return value(); }
};

template<>
struct DataType< ::tr_main::PlanCommand > {
  static const char* value()
  {
    return "tr_main/PlanCommand";
  }

  static const char* value(const ::tr_main::PlanCommand&) { return value(); }
};


// service_traits::MD5Sum< ::tr_main::PlanCommandRequest> should match 
// service_traits::MD5Sum< ::tr_main::PlanCommand > 
template<>
struct MD5Sum< ::tr_main::PlanCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tr_main::PlanCommand >::value();
  }
  static const char* value(const ::tr_main::PlanCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tr_main::PlanCommandRequest> should match 
// service_traits::DataType< ::tr_main::PlanCommand > 
template<>
struct DataType< ::tr_main::PlanCommandRequest>
{
  static const char* value()
  {
    return DataType< ::tr_main::PlanCommand >::value();
  }
  static const char* value(const ::tr_main::PlanCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tr_main::PlanCommandResponse> should match 
// service_traits::MD5Sum< ::tr_main::PlanCommand > 
template<>
struct MD5Sum< ::tr_main::PlanCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tr_main::PlanCommand >::value();
  }
  static const char* value(const ::tr_main::PlanCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tr_main::PlanCommandResponse> should match 
// service_traits::DataType< ::tr_main::PlanCommand > 
template<>
struct DataType< ::tr_main::PlanCommandResponse>
{
  static const char* value()
  {
    return DataType< ::tr_main::PlanCommand >::value();
  }
  static const char* value(const ::tr_main::PlanCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TR_MAIN_MESSAGE_PLANCOMMAND_H
