// Generated by gencpp from file tr_main/PlanParamResponse.msg
// DO NOT EDIT!


#ifndef TR_MAIN_MESSAGE_PLANPARAMRESPONSE_H
#define TR_MAIN_MESSAGE_PLANPARAMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tr_main
{
template <class ContainerAllocator>
struct PlanParamResponse_
{
  typedef PlanParamResponse_<ContainerAllocator> Type;

  PlanParamResponse_()
    : result(0.0)  {
    }
  PlanParamResponse_(const ContainerAllocator& _alloc)
    : result(0.0)  {
  (void)_alloc;
    }



   typedef double _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::tr_main::PlanParamResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tr_main::PlanParamResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlanParamResponse_

typedef ::tr_main::PlanParamResponse_<std::allocator<void> > PlanParamResponse;

typedef boost::shared_ptr< ::tr_main::PlanParamResponse > PlanParamResponsePtr;
typedef boost::shared_ptr< ::tr_main::PlanParamResponse const> PlanParamResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tr_main::PlanParamResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tr_main::PlanParamResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tr_main

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tr_main': ['/home/gagne/catkin_ws/src/tr_main/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tr_main::PlanParamResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tr_main::PlanParamResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tr_main::PlanParamResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tr_main::PlanParamResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tr_main::PlanParamResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tr_main::PlanParamResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tr_main::PlanParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "254fb2d8c4e08eff5dc6a560ed51dd52";
  }

  static const char* value(const ::tr_main::PlanParamResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x254fb2d8c4e08effULL;
  static const uint64_t static_value2 = 0x5dc6a560ed51dd52ULL;
};

template<class ContainerAllocator>
struct DataType< ::tr_main::PlanParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tr_main/PlanParamResponse";
  }

  static const char* value(const ::tr_main::PlanParamResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tr_main::PlanParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 result\n\
\n\
";
  }

  static const char* value(const ::tr_main::PlanParamResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tr_main::PlanParamResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanParamResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tr_main::PlanParamResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tr_main::PlanParamResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<double>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TR_MAIN_MESSAGE_PLANPARAMRESPONSE_H
